client_ID="YOUR_CLIENT_ID"
client_SECRET='YOUR_CLIENT_SECERET'   
redirect_url='http://localhost:9000'

EMAIL_ADDRESS = 'YOUR_EMAIL_ADDRESS'
EMAIL_PASSWORD = 'YOUR_EMAIL_PASS'
TARGET_ADDRESS = "TARGET_EMAIL"
